name: word-to-pdf

services:
  # docx-to-pdf:
  #   build: ./docx-to-pdf
  #   ports:
  #     - "8085:8080"
  #   environment:
  #     - pool.size=2
  
  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "8090:3000"
    command:
      - "gotenberg"
      - "--libreoffice-restart-after=50"
      - "--libreoffice-max-queue-size=20"

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: word-to-pdf
      POSTGRES_PASSWORD: word-to-pdf
      POSTGRES_DB: word-to-pdf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U word-to-pdf"]
      interval: 1s

  reverse-proxy: 
    image: traefik:v3.3
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entryPoints.websecure.address=:443"
      - "--providers.file.filename=/etc/traefik/traefik_dynamic.yml"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dev-certs:/etc/traefik/certs
      - ./traefik/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml
    ports:
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
